# Midterm Exam Part II (30 pts)

In [1]:
import numpy as np

### Question 1 (10 pts)

Consider a system of linear equations:
$$\begin{cases} 
2x_1+x_2 -2x_3=5 
\\ 2x_1+3x_2=4 \\
3x_1-4x_3 = -6  \end{cases}\tag{1}$$

In [2]:
# Define the matrix A as the coefficients of the linear equations
A = np.array([[2, 1, -2], 
              [2, 3, 0], 
              [3, 0, -4]]) # Replacing None with your code. 

# Write your code to define C as the right hand side of the linear equations.
C = np.array([5, 4, -6]) # Replacing None with your code.
print(A)
print(C)

[[ 2  1 -2]
 [ 2  3  0]
 [ 3  0 -4]]
[ 5  4 -6]


In [3]:
# Write your code to calculate the solution of the linear equations using the 
# matrix inverse method. Do not directly use np.linalg.solve function.
X = np.linalg.inv(A)
# write your code by replacing None with your code.
print(X)

[[-6.   2.   3. ]
 [ 4.  -1.  -2. ]
 [-4.5  1.5  2. ]]


In [5]:
#we can also use np.linalg.solve function to solve the system of linear equations
X1 = np.linalg.solve(A,C) # write your code to solve the equation with 
            #np.linalg.solve function
print(X1)

[-40.   28.  -28.5]


### Question 2 (15 pts): 

Consider vectors:

$x = \begin{bmatrix} 
2 \\ 3 \\ 5 \\ -3 \end{bmatrix}$, $y =\begin{bmatrix} 3 \\ 1 \\ -2 \\ 2 \end{bmatrix}$, $z =\begin{bmatrix} 1 \\ 2 \\ -1 \\ 1 \end{bmatrix}$, and $u =\begin{bmatrix} 3 \\ 0 \\ 5 \\ -3 \end{bmatrix}$

#### Part 1: Determine if these four vectors are linearly dependent

In [14]:
# Define vectors x, y, z, u
x = np.array([2, 3, 5, -3])
y = np.array([3, 1, -2, 2])
z = np.array([1, 2, -1, 1])
u = np.array([3, 0, 5, -3])

A = np.column_stack((x, y, z, u)) # Replacing None with your code to represent x,y,z,u in the form of matrix

# Print the matrix A
print("Matrix A:")
print(A)

det_A = np.linalg.det(A[:3, :3])
print("\nDeterminant of A:")
print(det_A) # Replacing None with your code to 
            #print the determinate of matrix A.
    


Matrix A:
[[ 2  3  1  3]
 [ 3  1  2  0]
 [ 5 -2 -1  5]
 [-3  2  1 -3]]

Determinant of A:
34.00000000000001


Base on the above result, are vectors x, y, and z are linearly dependent? (Delete the part that is not correct and keep the one that is correct)

Answer: they are linearly **(independent)** since the determinant of A is not equal to zero.

#### Part 2 Determine if any pair of x, y, and z are orthogonal.

In [16]:
# Represent x, y, and z as np arrays (1D or 2D)
x = np.array([2, 3, 5, -3]) #write your code to create a 1D array of the above x
y = np.array([3, 1, -2, 2]) #write your code to create a 1D array of the above y
z = np.array([1, 2, -1, 1]) #write your code to create a 1D array of the above z
              
# Write your code below to calculate the dot product between x, y, and z 
# and print the result.
# Dot product of x and y
dot_product_xy = np.dot(x, y)
print("Dot product of x and y:", dot_product_xy)

# Dot product of y and z
dot_product_yz = np.dot(y, z)
print("Dot product of y and z:", dot_product_yz)

# Dot product of x and z
dot_product_xz = np.dot(x, z)
print("Dot product of x and z:", dot_product_xz)


Dot product of x and y: -7
Dot product of y and z: 9
Dot product of x and z: 0


Based on the above results, which pairs of x, y, and z are orthogonal

List pairs of x, y, z that are orthogonal:

**Answer: Based on the above results, x and z are orthogonal since they are equal to zero**

#### Part 3: Calulate Norms of vectors:

Write code to calculate the $L_1$, $L_2$, and $L_\infty$ of $x$. 

In [24]:
norm1_x = np.sum(np.abs(x)) #write your code to calculate the L1 norm of x
norm2_x = np.sqrt(np.sum(x**2)) #write your code to calculate the L2 norm of x
norminf_x = np.max(np.abs(x)) #write your code to calculate the L infinity norm of x

print(norm1_x, norm2_x, norminf_x) #print the L1, L2, and L infinity norm of x
                                    #Do not change this code

13 6.855654600401044 5


### Question 3 (5pts) Eigenvalues and Eigenvectors

Let $A = \begin{bmatrix}
3 & 7 & -1 \\
7 & -1 & 3 \\
-1 & 3 & 4
\end{bmatrix}$.

Write code to calculate eigenvalues and eigenvectors of $A$

In [26]:
A = np.array([[3, 7, -1],
              [7, -1, 3],
              [-1, 3, 4]]) # Replacing None with your code to represent the matrix A.
# Write your code to calculate three eigen values and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

L1 = eigenvalues[0] #The first eigen value, relpace None with your code
v1 = eigenvectors[:, 0] #The first eigen vector, relpace None with your code
L2 = eigenvalues[1] #The second eigen value, relpace None with your code
v2 = eigenvectors[:, 1] #The second eigen vector, relpace None with your code
L3 = eigenvalues[2] #The third eigen value, relpace None with your code
v3 = eigenvectors[:, 2] #The third eigen vector, relpace None with your code

print(L1, v1) # print the first eigen value and the first eigen vector
print(L2, v2) # print the second eigen value and the second eigen vector
print(L3, v3) # print the third eigen value and the third

-7.094673165098975 [ 0.56730322 -0.78064585  0.2622196 ]
8.538615070110026 [-0.74214863 -0.62264607 -0.24804694]
4.556058094988959 [-0.35690682  0.05388809  0.93258436]


Write code to verify that the eigenvalues and eigenvectores you calculated are correct. You need to verify that:

$A v1 = \lambda v1$. 

In [31]:
print("A v1:", A @ v1) # write your code to print A v1
print("L1 v1:", L1 * v1) # write your code to print L1 v1
print("\nA v2:", A @ v2) # write your code to print A v2
print("L2 v2:", L2 * v2) # write your code to print L2 v2
print("\nA v3:", A @ v3) # write your code to print A v3
print("L3 v3:", L3 * v3) # write your code to print L3 v3
print("The 𝐴𝑣1=𝜆𝑣1, 𝐴𝑣2=𝜆𝑣2, and 𝐴𝑣3=𝜆𝑣3")

A v1: [-4.0248309   5.53842716 -1.86036236]
L1 v1: [-4.0248309   5.53842716 -1.86036236]

A v2: [-6.33692144 -5.31653514 -2.11797736]
L2 v2: [-6.33692144 -5.31653514 -2.11797736]

A v3: [-1.62608821  0.24551726  4.24890854]
L3 v3: [-1.62608821  0.24551726  4.24890854]
The 𝐴𝑣1=𝜆𝑣1, 𝐴𝑣2=𝜆𝑣2, and 𝐴𝑣3=𝜆𝑣3
